kasko/docs

source/products/friday/zusatzfahrer/rest-api.rst
https://kaskoltd.atlassian.net/browse/PROD-3035
=> Prod 3035 Add docs about start_date and end_date

source/products/visana/index.rst, source/products/visana/private-liability-contents/index.rst, source/products/visana/private-liability-contents/webapp.rst
Reference ticket: [PROD-3419](https://kaskoltd.atlassian.net/browse/PROD-3419)
=> Adds Visana [PROD-3419]

source/products/mobiliar/flixbus/rest-api.rst
Flixbus update docs depend on new Pricing excel
=> PROD-3761 Flixbus update docs depend on new Pricing excel

source/webhooks.rst
Related to https://kaskoltd.atlassian.net/browse/PROD-4060
=> Add a section on policy.updated webhook event

source/products/baloise/my-camper/index.rst, source/products/baloise/my-camper/rest-api.rst, source/products/mobiliar/flixbus/rest-api.rst
https://kaskoltd.atlassian.net/browse/PROD-4532
PROD-4532 Create API documentation, for my camper.
=> PROD-4532 create API documetation

source/products/baloise/my-camper/rest-api.rst
https://kaskoltd.atlassian.net/browse/PROD-4532
=> PROD-4532 My camper, add new field `booking_number`

source/index.rst, source/kasko_js/index.rst, source/kasko_js/v1.rst, source/kasko_js/v2.rst
Add basic information about the usage of KASKO js v2.
=> Kasko js v2

source/products/baloise/cyber-sme/index.rst
Part of webapp's [cleanup](https://github.com/kasko/baloise-cyber-sme-web-app/pull/105).
=> fix: change `item_id` for Baloise Cyber SME

source/products/index.rst, source/products/roland/getsafebaserate/index.rst, source/products/roland/getsafebaserate/rest-api.rst, source/products/roland/index.rst
Relevant ticket: https://kaskoltd.atlassian.net/browse/PROD-5067
=> PROD-5067 Roland Getsafe Base Rate Docs

source/products/roland/getsafebaserate/rest-api.rst, source/products/zurich/index.rst, source/products/zurich/smarthome/index.rst, source/products/zurich/smarthome/rest-api.rst
Relevant ticket - https://kaskoltd.atlassian.net/browse/PROD-5024
=> PROD-5024 Zurich Smarthome docs

source/products/roland/getsafebaserate/rest-api.rst
Update docs with extra fields in quota data and request
=> PROD-5024 Getsafe Base Rate docs update

source/products/baloise/holiday_v2/index.rst, source/products/baloise/holiday_v2/rest-api.rst
https://kaskoltd.atlassian.net/browse/PROD-5219
=> PROD-5219 Add Holiday v2 documentation

source/products/hansemerkur/dog-surgery/index.rst, source/products/index.rst, source/products/occ/index.rst, source/products/occ/vintage-car/index.rst, source/products/occ/vintage-car/webapp.rst, source/products/zurich/cyber-sme/index.rst, source/products/zurich/smarthome/index.rst, source/products/zurich/zurich-do/index.rst
[PROD-5570](https://kaskoltd.atlassian.net/browse/PROD-5570)
=> PROD-5570: add OCC - Vintage Car product

source/products/baloise/relocation/rest-api.rst
https://kaskoltd.atlassian.net/browse/PROD-5255
=> PROD-5255 Add cancellation example.

source/products/occ/vintage-car/agent/rest-api.rst, source/products/occ/vintage-car/broker/rest-api.rst, source/products/occ/vintage-car/index.rst, source/products/occ/vintage-car/user/rest-api.rst
https://kaskoltd.atlassian.net/browse/PROD-5690
=> PROD-5690 Add other two occ items.

source/products/roland/getsafebaserate/rest-api.rst
https://kaskoltd.atlassian.net/browse/PROD-5544
=> PROD-5544 Getsafe Base Rate Docs Update

source/products/zurich/car-contents/index.rst, source/products/zurich/car-contents/webapp.rst, source/products/zurich/index.rst
=> Add Car Contents

source/products/baloise/travel-layer-cover/index.rst, source/products/baloise/travel-layer-cover/rest-api.rst, source/products/occ/vintage-car/broker/rest-api.rst
https://kaskoltd.atlassian.net/browse/PROD-5995
=> PROD-5995 Add broker number, change my-camper to travel layer cover

source/products/index.rst, source/products/renault/commercial-test-drive/index.rst, source/products/renault/commercial-test-drive/webapp.rst, source/products/renault/index.rst, source/products/renault/private-test-drive/index.rst, source/products/renault/private-test-drive/webapp.rst, source/products/renault/replacement-car/index.rst, source/products/renault/replacement-car/webapp.rst
- RCI - Commercial Test Drive
- RCI - Replacement Car
- RCI - Private Test Drive
=> add Renault products

source/products/index.rst, source/products/neodigital/index.rst, source/products/neodigital/multi-item/index.rst, source/products/neodigital/multi-item/rest-api.rst
https://kaskoltd.atlassian.net/browse/PROD-6776
=> NeoDigital API docs

source/products/hansemerkur/index.rst, source/products/hansemerkur/softfair/index.rst, source/products/hansemerkur/softfair/rest-api.rst
https://kaskoltd.atlassian.net/browse/PROD-6892
=> Softfair API Docs

source/products/hansemerkur/cat/index.rst, source/products/hansemerkur/cat/rest-api.rst, source/products/hansemerkur/index.rst
=> PROD-6846 HanseMerkur Cat API Docs

source/products/oab/household/index.rst, source/products/oab/household/rest-api.rst
https://kaskoltd.atlassian.net/browse/PROD-5756
=> PROD-5756 Create api documentation for oab.

source/products/hansemerkur/cat/rest-api.rst
https://kaskoltd.atlassian.net/browse/PROD-6846
=> HanseMerkur Cat naming update

source/products/zurich/cyber-sme-v2/index.rst, source/products/zurich/cyber-sme-v2/webapp.rst
https://github.com/kasko/v2-zurich-cyber-sme-web-app/pull/1
=> Add zurich cyber sme v2 webapp

source/products/zurich/index.rst, source/products/zurich/makler/index.rst, source/products/zurich/makler/makler-cyber-sme-v2-low/index.rst, source/products/zurich/makler/makler-cyber-sme-v2-low/rest-api.rst, source/products/zurich/makler/makler-cyber-sme-v2-min/index.rst, source/products/zurich/makler/makler-cyber-sme-v2-min/rest-api.rst
https://kaskoltd.atlassian.net/browse/PROD-7401
=> Zurich Cyber SME V2 low/min docs

source/products/occ/allianz-vintage-car/agent/rest-api.rst, source/products/occ/allianz-vintage-car/broker/rest-api.rst, source/products/occ/allianz-vintage-car/index.rst, source/products/occ/allianz-vintage-car/user/rest-api.rst, source/products/occ/allianz-vintage-car/webapp.rst, source/products/occ/index.rst
=> PROD-9628 OCC Allianz API docs

source/products/occ/allianz-vintage-car/agent/rest-api.rst, source/products/occ/allianz-vintage-car/broker/rest-api.rst, source/products/occ/allianz-vintage-car/user/rest-api.rst
Replace real email address in payloads to generic test one.
=> PROD-9628 Email fix

source/products/zurich/makler/index.rst, source/products/zurich/makler/makler-cyber-sme-v2-high/index.rst, source/products/zurich/makler/makler-cyber-sme-v2-high/rest-api.rst, source/products/zurich/makler/makler-cyber-sme-v2-min/rest-api.rst
Add/update Zurich/GV24 API docs
https://kasko.atlassian.net/browse/PROD-12453
=> PROD-12453 Zurich/GV24 API docs

source/products/zurich/makler/makler-cyber-sme-v2-high/rest-api.rst
=> PROD_12453 Header fix

source/products/roland/getsafe/rest-api.rst, source/products/roland/getsafebaserate/rest-api.rst
We had deprecated policy update docs for Roland. Changed to new method, as old one is causing issues.
https://kasko.atlassian.net/browse/PROD-12608
=> PROD-12608 Updated Roland api docs

source/products/roland/getsafe-v3/index.rst, source/products/roland/getsafe-v3/rest-api.rst, source/products/roland/index.rst
https://kasko.atlassian.net/browse/PROD-12709
=> PROD-12709 Getsafe Legal insurance request examples

source/products/roland/getsafe/rest-api.rst
Getsafe comfort rate policy patch documentation update.
=> Getsafe comfort rate policy patch documentation update.

source/products/roland/getsafe-v3/rest-api.rst
Updated getsafe all tarifs documentation
=> Updated getsafe all tarifs documentation
